# frontend/Dockerfile-dev

# This is the build file for the frontend module, Docker will use this to setup the frontend container image.

# Installs the node image
FROM node

# Creates the frontend directory in the container
RUN mkdir -p /app/frontend
# Sets the working directory to the frontend directory
WORKDIR /app/frontend

# Copies the yarn.lock file to the container
COPY yarn.lock /app/frontend/
# Copies the package.json to the container
COPY package*.json /app/frontend/

# Installs the frontend dependencies
RUN yarn install

# Copies the files from the frontend directory to the container
COPY . /app/frontend/

# Runs the frontend
CMD ["yarn", "dev"]